name = "QuantumCircuits"
uuid = "542f4203-40d5-4497-9446-add4998b2a81"
authors = ["Piyush Kumar Singh <pksx9120@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
